### PR TITLE
Django40

### PR DESCRIPTION
**Pull request by PetrDlouhy**

### CODE REVIEW

**Comment by PetrDlouhy** [comment]
@Benoss Could you please release version with Django 4.0 support on PyPI?

**Comment by barseghyanartur** [comment]
For me the buttons (`Show Json Body` and `Show Json Response `) don't work.

**settings/dev.py**

```python
DEBUG_TOOLBAR_PANELS = (
    # Defaults
    # 'debug_toolbar.panels.versions.VersionsPanel',
    "debug_toolbar.panels.timer.TimerPanel",
    "debug_toolbar.panels.settings.SettingsPanel",
    "debug_toolbar.panels.headers.HeadersPanel",
    "debug_toolbar.panels.request.RequestPanel",
    "debug_toolbar.panels.sql.SQLPanel",
    # 'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    # 'debug_toolbar.panels.templates.TemplatesPanel',
    "debug_toolbar.panels.cache.CachePanel",
    "debug_toolbar.panels.signals.SignalsPanel",
    "debug_toolbar.panels.logging.LoggingPanel",
    "debug_toolbar.panels.redirects.RedirectsPanel",
    # Additional
    "elastic_panel.panel.ElasticDebugPanel",
)

INSTALLED_APPS += [
    "debug_toolbar",
    "elastic_panel",
]
```

Do they work for you?

**Comment by PetrDlouhy** [comment]
@barseghyanartur Doesn't work for me either. It seems, there is some problem with loading `elastic_panel.js`.

**Comment by barseghyanartur** [comment]
@PetrDlouhy:

Works for me now. Two PRs have been merged into master yesterday. If you `pip install` latest master, it will work.

**Pull request merged**
